### ISSUE TITLE
Detail information for igxess.dll, libxess.dll, WinPixEventRuntime.dll, XeFX.dll, XeFX_Load.dll

### ISSUE THREAD

**Issue by JustinKJChen** [intel/xess#15]
Any introduction for igxess.dll, libxess.dll, WinPixEventRuntime.dll, XeFX.dll, XeFX_Load.dll? If we want to know what's feature, architecture and work flow...

**Comment by Rigelstars** [comment]
> Any introduction for igxess.dll, libxess.dll, WinPixEventRuntime.dll, XeFX.dll, XeFX_Load.dll? If we want to know what's feature, architecture and work flow...

I want to know too

**Comment by xess-intel** [comment]
Starting with XeSS 1.2.0, we no longer ship all DLLs mentioned above. An application only needs to redistribute libxess.dll with it.
