### ISSUE TITLE
Output color range problem

### ISSUE THREAD

**Issue by cdozdil** [intel/xess#19]
Hello,

I think there is a problem on output color calculations when color texture has wide (like 0.0f-64000.0f) range . Input color texture have correct details but output texture comes out crushed and with missing details.

For example this is input color texture:
![image](https://github.com/intel/xess/assets/35529761/3443bcf2-579a-405e-96d6-c2a360a9a133)

This is the output texture from xess:
![image](https://github.com/intel/xess/assets/35529761/3ff95e70-aa73-452e-9e25-e8ef9afefc1f)

Input color texture have a color value range of 0-64000 but output texture only have 0-380 (and this 380 is like a limit on XeSS?)

I am attaching dump of this frame too.
[XessDump.zip](https://github.com/intel/xess/files/13816488/XessDump.zip)

One final thing, dump is taken with AutoExposure but i am getting same results with using ExposureTexture too.

**Comment by xess-intel** [comment]
@cdozdil thank you for reporting an issue! This has been fixed in recently released XeSS 1.3, check it out!

**Comment by cdozdil** [comment]
@xess-intel Just checked and indeed it is fixed! Thanks for hard work! 

I would like to give a feedback about process, maybe an information message like "we are investigating it" or "our team will check" etc would be nice. Because I wasn't expecting a fix at this point at all (after long silence) and even fixed fixed it in a hacky way (compressing/decompressing colors with a compute shader & using autoexposure to correct colors). 

Anyway thanks again and it's good to know there is someone is listening us at Intel side :)
